version: "3.8"
services:
  mysql:
    image: mysql
    container_name: dvd_mysql
    volumes:
      - ./fixtures:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dvdStore
      - MYSQL_USER=mysqli
      - MYSQL_PASSWORD=mysqli
    ports:
      - "8001:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dvd_phpmyadmin
    ports:
      - "8002:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  nginx:
    image: nginx:alpine
    container_name: dvd_nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8004:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: dvd_php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor:cached
    depends_on:
      - mysql
networks:
  mysql:
  php-fpm: