home:
    path: /
    controller: App\Controller\homeController
#user#
register:
    path: /register
    controller: App\Controller\RegistrationController
login:
    path: /login
    controller: App\Controller\SecurityController
logout:
    path: /logout
    controller: App\Controller\SecurityController
#catégory#
category:
    path: /categories
    controller: App\Controller\category\AllCategoriesController

#product#
product:
    path: /product
    controller: App\Controller\product\AllProductController
#product#
oneProduct:
    path: /product/ourProduct/{slug}
    controller: App\Controller\product\OneProductController
